theme: jekyll-theme-leap-day


title: Ting Data Science Blog
description: A colletion of data science work

show_downloads: true

About Me: "I am a very happy persione"
github: https://github.com/sittingman
linkedin: https://www.linkedin.com/in/sittingman1/
 
 
linkedin: true